---
- name: Import AAP
  hosts: 192.168.1.10
  become: true
  vars:
      ansible_python_interpreter: /usr/bin/python3.9
  tasks:
        
  - name: Load test_job template
    awx.awx.import:
        controller_host: 192.168.1.10
        controller_username: admin
        controller_password: admin123
        validate_certs: false
        assets: "{{ lookup('file', 'test_jobs.json') | from_json() }}"
