---
- name: Import AAP
  hosts: 192.168.1.10
  vars:
      ansible_python_interpreter: /usr/bin/python3.9
      remote_user: root
  tasks:

  - name: Export Jobs
    awx.awx.export:
        controller_host: 192.168.1.40
        controller_username: admin
        controller_password: admin123
        job_templates: "PING_TEST"
        validate_certs: False
        all: True
    register: export_output

  - name: Import all assets from our export
    awx.awx.import:
        controller_host: 192.168.1.10
        controller_username: admin
        controller_password: admin123
        validate_certs: False
        assets: "{{ export_output.assets }}"

